Add cloudflare
FriendsOfShopware/FroshPlatformThumbnailProcessor pull request #21
Opened 2021-06-24 18:46 UTC by Isengo1989

Add cloudflare template info and readme

2021-06-24 19:14 UTC, tinect requested changes

2021-06-24 19:14 UTC, tinect commented on README.md
> +will become `https://yourshop.com/cdn-cgi/image/width%3D3000%2Cheight%3D3000quality%3D75/media/64/fd/98/1624446656/ff310899329c4d94855a096a26b02d5e.jpg`
```suggestion
Template example: `{mediaUrl}/cdn-cgi/image/width={width},height={height},quality=75/{mediaPath}`  
will become `https://yourshop.com/cdn-cgi/image/width%3D3000%2Cheight%3D3000%2Cquality%3D75/media/64/fd/98/1624446656/ff310899329c4d94855a096a26b02d5e.jpg`
```

2021-06-24 19:14 UTC, tinect commented on README.md
> +`Has a lossless image optimization and big hosters have their NFS connected in their contracts directly to cloudflare`
```suggestion
`Has a lossless image optimization and big hosters have their NFS connected in their contracts directly to cloudflare. Available in Business and Enterprise Plans.`  
```

2021-06-24 19:14 UTC, tinect commented on README.md
> +### cloudflare [Link](https://www.cloudflare.com)
```suggestion
### Cloudflare Image Resizing [Link](https://developers.cloudflare.com/images/)
```

2021-06-24 19:14 UTC, tinect commented on src/Resources/app/administration/src/frosh-thumbnail-processor-info-texts.html.twig
> +        </p>
```suggestion
        <h4 class="supports-headline"><a href="https://www.cloudflare.com" target="_blank">cloudflare</a></h4>
        <blockquote>Opinion: fast and including webp</blockquote>
        <p class="supports-description">
            Has a lossless image optimization and big hosters have their NFS connected in their contracts directly to cloudflare. Available in Business and Enterprise Plans.<br><br>
            <sw-text-field label="Template example" size="small" :copyable="true"
                           value="{mediaUrl}/cdn-cgi/image/width={width},height={height},quality=75/{mediaPath}"/>
            will become
            <code>https://yourshop.com/cdn-cgi/image/width%3D3000%2Cheight%3D3000%2Cquality%3D75/media/64/fd/98/1624446656/ff310899329c4d94855a096a26b02d5e.jpg</code>
        </p>
```

2021-06-25 16:53 UTC, Isengo1989 commented
@tinect there was an overlap - alright like that?

2021-06-25 19:37 UTC, tinect requested changes

2021-06-25 19:37 UTC, tinect commented on README.md
> +will become `https://yourshop.com/cdn-cgi/image/width%3D3000%2Cheight%3D3000quality%3D85/media/64/fd/98/1624446656/ff310899329c4d94855a096a26b02d5e.jpg`
The example result link isn't correct. The comma and format is missing.

2021-06-25 19:37 UTC, tinect commented on src/Resources/app/administration/src/frosh-thumbnail-processor-info-texts.html.twig
> +            <code>https://yourshop.com/cdn-cgi/image/width%3D3000%2Cheight%3D3000quality%3D85/media/64/fd/98/1624446656/ff310899329c4d94855a096a26b02d5e.jpg</code>
The example result link isn't correct. The comma and format is missing.

2021-06-25 19:41 UTC, tinect requested changes

2021-06-25 19:41 UTC, tinect commented on src/Resources/app/administration/src/frosh-thumbnail-processor-info-texts.html.twig
> +        <blockquote>Opinion: many options but only for business and enterprise customers</blockquote>
```suggestion
        <blockquote>Opinion: many options but only for business and enterprise customers. Has no auto detection of supported formats of visitor. So you are pinned to jpeg, webp or avif.</blockquote>
```

2021-06-25 19:41 UTC, tinect commented on README.md
> +An image cache & resize service. Manipulate images on-the-fly with a worldwide cache.
```suggestion
`Opinion: many options but only for business and enterprise customers. Has no auto detection of supported formats of visitor. So you are pinned to jpeg, webp or avif.`  
Has a lossless image optimization and big hosters have their NFS connected in their contracts directly to cloudflare 
```

2021-06-27 08:15 UTC, Isengo1989 commented
Resolved the issues before with comma already in a change and commited your changes regarding auto webp switch

2021-07-13 20:34 UTC, Isengo1989 commented
@tinect I did find the auto option, so now IE and Old Safaris work too, also updated the encoded URL.

2021-07-14 18:56 UTC, merged