feat: shopware 6.5
FriendsOfShopware/FroshPlatformThumbnailProcessor pull request #79
Opened 2023-02-16 21:26 UTC by stefanpoensgen

2023-02-18 23:26 UTC, tinect commented
Thank you. Could you please remove `height` from the thumbnailUrlTemplate?

2023-02-22 19:17 UTC, shyim commented on src/Storefront/Framework/Twig/Extension/UrlEncodingTwigFilter.php
> +            new TwigFilter('frosh_encode_url', fn (?string $mediaUrl): ?string => $this->encodeUrl($mediaUrl)),
```suggestion
            new TwigFilter('frosh_encode_url', $this->encodeUrl(...)),
```

2023-03-14 21:36 UTC, tinect requested changes
@stefanpoensgen Could you please verify the changes in shopwares ThumbnailService?

EDIT: done

2023-04-03 20:41 UTC, tinect commented on composer.json
> +        "shopware/core": "^6.5.0"
```suggestion
        "shopware/core": "~6.5.0"
```

2023-04-16 18:43 UTC, tinect commented
- [ ] use PhpParser? we just need to overwrite the private method `createThumbnailsForSizes` and set `$strict` to false in `updateThumbnails`

2023-04-16 20:17 UTC, tinect commented
@stefanpoensgen please test :-)

2023-04-16 20:34 UTC, tinect approved these changes

2023-05-06 15:47 UTC, tinect commented
- [ ] theme:compile broken

2023-05-06 23:16 UTC, merged